### ISSUE TITLE
Error in visualization (Mac OS X 10.11)

### ISSUE THREAD

**Issue by ghost** [symoro/symoro#10]
A problem occurs when I start the visualization on a robot on my Mac. I installed the software Symoro last friday and it works fine except for the visualization. I don't understand what doesn't work between PyOpenGL and Symoro. Here are the logs that appear in the Terminal when I start the visualization `quentin:bin quentinfrancois$ python symoro-bin.py run
Traceback (most recent call last):
  File "/Users/quentinfrancois/Applications/symoro/symoroviz/graphics.py", line 251, in OnPaintAll
    self.OnDraw()
  File "/Users/quentinfrancois/Applications/symoro/symoroviz/graphics.py", line 375, in OnDraw
    self.base.draw()
  File "/Users/quentinfrancois/Applications/symoro/symoroviz/objects.py", line 66, in draw
    child.draw()
  File "/Users/quentinfrancois/Applications/symoro/symoroviz/objects.py", line 138, in draw
    self.draw_rod(shift)
  File "/Users/quentinfrancois/Applications/symoro/symoroviz/objects.py", line 97, in draw_rod
    gl.glVertexPointer(3, gl.GL_FLOAT, 0, self.rod_vertices)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/wrapper.py", line 808, in wrapperCall
    cArguments,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/contextdata.py", line 41, in getContext
    """Attempt to retrieve context when no valid context"""
OpenGL.error.Error: Attempt to retrieve context when no valid context`

**Comment by BKhomutenko** [comment]
Hi

Which branch are you using?
If you are using master, then try GeometryFix branhc

Could you also tell for which purposes you are using the software?

Bogdan

**Comment by ghost** [comment]
Hi

I used the master branch. I just tested the GeometryFix branch and it works !!!!!! Thank's a lot !!
Out of curiosity, what is the difference between these two branches ?

Actually, I'm a student and I work with my professor in the AVR team of the Icube laboratory in Strasbourg for my internship. I heard that some of members of this team work with the IRCCyn laboratory. So I installed the software for my professor and I will test the soft with two simple robots. After that, but it is not sure with the short time I have, my goal is to make a script in Maple which reads a file .txt generated by Symoro and which makes the equations directly usable in Maple. I don't know for what purpose my professor wants this functionality. I will ask him.

**Comment by ghost** [comment]
I have worked with Symoro since two days and the modelization of open-loop robots works but not closed-loop robots. I took the robot "two-loops" in the examples available and I start the visualization. When I clicked on the radio button "make loops" I have these logs that appear on the terminal
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 640, in OnSelectLoops
    self.canvas.solve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 235, in solve
    if self.loop_iter():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 249, in loop_iter
    T = np.array(self.Tloop[i, j](q))
KeyError: (9, 11)`

Is it specific on the Mac platform or it is normal ?

**Comment by ngartner** [comment]
No that's a problem in the Symoro Code... KeyError means there is a problem with the dictionnary Tloop. The error should be raised on any computer.

However with the GeometryFix installed on my computer I have no problem to use the visualisation module with the two-loops example. Did you modify something ? Or delete some values ?

Can you get your .par in the symoro_robot file directory and drop it here ?

**Comment by BKhomutenko** [comment]
Hi,
In my case close loops works just fine with two loops. And I don't have an access to a mac to figure it out.

Concerning maple, I think that it breaks the idea of symoro. Its output is supposed to be used directly in numeric computations. If you need more different symbolic results, it is better to extend SYMORO itself.
The main advantage of Symoro is that it's open-source and you don't have to pay for it, while you don't actually need any advanced symbolic stuff to model robots.
Of course it's just my opinion and you may have a good reason to use Maple after

**Comment by ghost** [comment]
ngartner :
I haven't changed anything in that file. Here it's the .par file I used :
[two-loops.par.zip](https://github.com/symoro/symoro/files/351722/two-loops.par.zip)

PS : I just installed the soft Symoro on Windows and I have the same problem with the robot 2 loops.

BKhomutenko :
I agree with you on that point but I think that my professor wants to work with Maple for his courses. I don't know why yet.

**Comment by Izzatbek** [comment]
Hi,

I just run symoro on my Mac OS X 10.11.5 (GeometryFix), works fine with **two-loops.par** above. And the button **make loops** works as expected without any errors.

Izzat

**Comment by ghost** [comment]
Here are the logs I receive when I start the visualisation
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 149, in OnSize
    self.setup_viewport()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 463, in setup_viewport
    self.SetCurrent(self.context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/glcanvas.py", line 140, in SetCurrent
    return _glcanvas.GLCanvas_SetCurrent(*args)
wx._core.PyAssertionError: C++ assertion "IsShownOnScreen()" failed at ./src/common/glcmn.cpp(60) in SetCurrent(): can't make hidden GL canvas current
2 2`

When I click on the make loops button 
`[4, 6, 7, 8] [9, 10]
def KC_gen(*args):
    from numpy import pi, sin, cos, sign
    from numpy import array, arctan2 as atan2, sqrt
    [th1,th2,th3,th4,th5,th6,th7,th8,th9,th10]=args[0]
    d4=1.0
    d7=1.0
    d3=1.0
    KC_gen_result=[[d4*sin(th9) + d7*sin(th7 + th9),0,d4*sin(th9),0,0,0],[d4*cos(th9) + d7*cos(th7 + th9),0,d4*cos(th9),-d7,0,0],[0,d3*sin(th10),0,0,0,0],[0,d3*cos(th10),0,-d7,0,0],[1,0,1,-1,1,0],[0,1,0,-1,0,1]]
    return KC_gen_result
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 640, in OnSelectLoops
    self.canvas.solve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 227, in solve
    self.generate_loop_fcn()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 284, in generate_loop_fcn
    T = DGM.compute(self.robo, symo, i, j, fast_form=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/pysymoro/geometry.py", line 254, in compute
    return dgm_acc.transform(i, j)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/pysymoro/geometry.py", line 380, in transform
    self.symo.trig_replace(T_res)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroutils/symbolmgr.py", line 73, in trig_replace
    all_cos = M.atoms(cos)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy/matrices/matrices.py", line 2972, in __getattr__
    "%s has no attribute %s." % (self.__class__.__name__, attr))
AttributeError: Transform has no attribute atoms.`

And when I click another time on the make loops button
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 640, in OnSelectLoops
    self.canvas.solve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 235, in solve
    if self.loop_iter():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 249, in loop_iter
    T = np.array(self.Tloop[i, j](q))
KeyError: (9, 11)`

There is an error with wxPython in the first logs. What version of wxPyhton have you on your Mac Izzatbek ? I have installed the version 2.9.5 for cocoa.

**Comment by Izzatbek** [comment]
I am using 3.0.2.0 osx-cocoa (classic).

I think I installed it with homebrew

**Comment by ghost** [comment]
How did you install it ?

**Comment by ngartner** [comment]
Well I guess the error you get when you click another time on the make loops button happens just because the datas are deleted after first error.

For the first error : 
- Maybe you have not installed properly wxPython and that's why you get the error while entering visualisation, try reinstall it
- Maybe you modified a source file of Python and deleted an _init_ () function, try reinstall Symoro GeometryFix

**Comment by Izzatbek** [comment]
I believe I run `brew install wxpython` with [homebrew](http://brew.sh).

**Comment by ghost** [comment]
I reinstall wxpyhton with homebrew and the first error has disappeared but the error of the make loops button is still there. Here are the logs since the start of the application
`quentin:bin quentinfrancois$ python symoro-bin.py
2 2
[4, 6, 7, 8] [9, 10]
def KC_gen(*args):
    from numpy import pi, sin, cos, sign
    from numpy import array, arctan2 as atan2, sqrt
    [th1,th2,th3,th4,th5,th6,th7,th8,th9,th10]=args[0]
    d4=1.0
    d7=1.0
    d3=1.0
    KC_gen_result=[[d4*sin(th9) + d7*sin(th7 + th9),0,d4*sin(th9),0,0,0],[d4*cos(th9) + d7*cos(th7 + th9),0,d4*cos(th9),-d7,0,0],[0,d3*sin(th10),0,0,0,0],[0,d3*cos(th10),0,-d7,0,0],[1,0,1,-1,1,0],[0,1,0,-1,0,1]]
    return KC_gen_result`

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 640, in OnSelectLoops
    self.canvas.solve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 227, in solve
    self.generate_loop_fcn()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroviz/graphics.py", line 284, in generate_loop_fcn
    T = DGM.compute(self.robo, symo, i, j, fast_form=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/pysymoro/geometry.py", line 254, in compute
    return dgm_acc.transform(i, j)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/pysymoro/geometry.py", line 380, in transform
    self.symo.trig_replace(T_res)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg/symoroutils/symbolmgr.py", line 73, in trig_replace
    all_cos = M.atoms(cos)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy/matrices/matrices.py", line 2972, in __getattr__
    "%s has no attribute %s." % (self.__class__.__name__, attr))
AttributeError: Transform has no attribute atoms.`

**Comment by ghost** [comment]
I just tested possibilities of Symoro and I saw that the only actions which work are transformation matrix and IGM - Paul Method.
For the others I have an error in the Terminal.

I think that my installation is probably different from you. Izzatbek, can you explain how did you install the different packages needed ? I have installed setuptools with easy_install, numpy and pyopengl with pip and sympy with the source files.

**Comment by Izzatbek** [comment]
I cannot tell you for sure because I did that a long time ago, but I just run `pip list` and saw in the list those items:
- numpy (1.10.4)
- PyOpenGL (3.1.0)
- PyOpenGL-accelerate (3.1.0)
- setuptools (8.0.2)
- sympy (0.7.6)
- wxPython (3.0.2.0)
- wxPython-common (3.0.2.0)

Seems like everything is installed with pip

**Comment by ngartner** [comment]
When you have made Symoro installation, didn't you get any error ? (Dependencies missing ?)

**Comment by ghost** [comment]
I run `pip list` too and I have:
- Django (1.9.7)
- nose (1.3.7)
- numpy (1.11.1)
- Pillow (3.3.0)
- pip (8.1.2)
- PyOpenGL (3.1.0)
- PyOpenGL-Demo (3.0.1b1)
- setuptools (23.1.0)
- symoro (0.2, /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/symoro-0.2-py2.7.egg)
- sympy (0.7.3)
- vboxapi (1.0)
- wxPython (3.0.2.0)
- wxPython-common (3.0.2.0)

I made the last installation of symoro today in order to check if my installation was correct and I had no error.

**Comment by ghost** [comment]
I find the problem. It was the version of sympy. You have the 0.7.6 version and on the web page it is written that symoro needs the 0.7.3. I tested symoro with the 0.7.6 version of sympy and the "make loops" with the loops robot works.
