### ISSUE TITLE
TypeError: symbolic boolean expression has no truth value

### ISSUE THREAD

**Issue by vijaravind** [symoro/symoro#3]
Traceback (most recent call last):
  File "/home/eloise/symoro/symoroui/layout.py", line 681, in OnTransformationMatrix
    geometry.direct_geometric(self.robo, frames, trig_subs)
  File "/home/eloise/symoro/pysymoro/geometry.py", line 484, in direct_geometric
    forced=True, trig_subs=trig_subs)
  File "/home/eloise/symoro/pysymoro/geometry.py", line 335, in dgm
    return _dgm_one(robo, symo, i, j, fast_form, forced, trig_subs)
  File "/home/eloise/symoro/pysymoro/geometry.py", line 271, in _dgm_one
    T = T.applyfunc(symo.CS12_simp)
  File "/usr/local/lib/python2.7/dist-packages/sympy/matrices/dense.py", line 470, in applyfunc
    out = self._new(self.rows, self.cols, list(map(f, self._mat)))
  File "/home/eloise/symoro/symoroutils/symbolmgr.py", line 87, in CS12_simp
    names.sort()
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/relational.py", line 111, in __nonzero__
    raise TypeError("symbolic boolean expression has no truth value.")
TypeError: symbolic boolean expression has no truth value.

**Comment by BKhomutenko** [comment]
I'm not sure, but maybe I've solved it. It was about robot parameters which were not symbols (If i'm not wrong, cause I was doing it few month ago) Try it with the GeometryFix version (I'm not sure even that this part of code is still there).
